# Generated by Django 5.1.2 on 2024-10-21 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_perfil_empresa_perfil_profesion_perfil_puesto_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='ciudad',
            field=models.CharField(default='debes agregar una ciudad', max_length=100),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='codigo_postal',
            field=models.CharField(default='debes agregar un codigo postal', max_length=10),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='direccion',
            field=models.CharField(default='debes agregar una direccion', max_length=100),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='empresa',
            field=models.CharField(default='debes agregar una empresa', max_length=100),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='estado',
            field=models.CharField(default='debes agregar un estado', max_length=100),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='fecha_nacimiento',
            field=models.DateField(default='2021-01-01'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='pais',
            field=models.CharField(default='debes agregar un pais', max_length=100),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='profesion',
            field=models.CharField(default='debes agregar una profesion', max_length=100),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='puesto_actual',
            field=models.CharField(default='debes agregar un puesto actual', max_length=100),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(default='debes agregar un telefono', max_length=10),
        ),
    ]
