# Generated by Django 5.1.2 on 2024-10-21 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_perfil_ciudad_alter_perfil_codigo_postal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(default='debes agregar un telefono', max_length=50),
        ),
    ]
