# Generated by Django 5.1.2 on 2024-10-21 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_perfil_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='codigo_postal',
            field=models.CharField(default='codigo postal', max_length=10),
        ),
    ]
