# Generated by Django 5.1.2 on 2024-10-25 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficio',
            name='publicacion',
        ),
        migrations.RemoveField(
            model_name='requisito',
            name='publicacion',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='requisitos',
            field=models.ManyToManyField(related_name='publicaciones_requisitos', to='front.requisito'),
        ),
    ]
