# Generated by Django 5.1.2 on 2024-10-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_remove_beneficio_publicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='requisitos',
            field=models.ManyToManyField(related_name='publicaciones', to='front.requisito'),
        ),
    ]
